In [ ]:
import pandas as pd

#Series - It is a 1-D array like object that can hold any data type.

data = [1,2,3,4,5]
series = pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
##CREATING SERIES FROM DICTONARY

##HERE WE WILL GIVE THE INDEX AS WELL AS THE VALUE

data = {'a':1,'b':2,'c':3,'d':4}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
#DATAFRAME

##CREATE A DATAFRAME FROM DICTIONARY

data = {
    'Name':['Krish','Siddharth','Anshul'],
    'Age':[30,22,21],
    'City':['Mumbai','Jabalpur','Jhansi']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age      City
0      Krish   30    Mumbai
1  Siddharth   22  Jabalpur
2     Anshul   21    Jhansi
<class 'pandas.core.frame.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['Krish', 30, 'Mumbai'],
       ['Siddharth', 22, 'Jabalpur'],
       ['Anshul', 21, 'Jhansi']], dtype=object)

In [13]:
##CREATE A DATAFRAME FROM A LIST OF DICTIONARIES 

data = [
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'Siddharth','Age':32,'City':'Bangalore'},
    {'Name':'Akshat','Age':32,'City':'Bangalore'},
    {'Name':'Krish','Age':32,'City':'Bangalore'},

]

pd.DataFrame(data)

        Name  Age       City
0      Krish   32  Bangalore
1  Siddharth   32  Bangalore
2     Akshat   32  Bangalore
3      Krish   32  Bangalore

In [70]:
##Loading dataset into python

df = pd.read_csv('sales_data.csv')
df.tail(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
##Accessing the elements
df['Transaction ID']

In [ ]:
##ACCESSING DATA THROUGH LOCATION
print(df.loc[1])
print("\n")
print(df.loc[1])

Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                         1
Unit Price                    499.99
Total Revenue                 499.99
Region                        Europe
Payment Method                PayPal
Name: 1, dtype: object


Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                         1
Unit Price                    499.99
Total Revenue                 499.99
Region                        Europe
Payment Method                PayPal
Name: 1, dtype: object

In [31]:
##ACCESSING DATA THROUGH INDEX LOCATION
df.iloc[4][1]

C:\Users\HP\AppData\Local\Temp\ipykernel_22700\1866479625.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[4][1]

'2024-01-05'

In [34]:
df.at[1,'Date']

'2024-01-02'

In [65]:
##DATA MANIPULATION WITH DATAFRAME
data = {
    'Name':['Krish','Siddharth','Anshul','Yash'],
    'Age':[30,22,21,23],
    'City':['Mumbai','Jabalpur','Jhansi','Indore']
}

df = pd.DataFrame(data)

In [66]:
##ADDING A COLUMN
df['Salary']=[100000,200000,150000,100000]

df

        Name  Age      City  Salary
0      Krish   30    Mumbai  100000
1  Siddharth   22  Jabalpur  200000
2     Anshul   21    Jhansi  150000
3       Yash   23    Indore  100000

In [67]:
##REMOVING A COLUMN

df.drop('Salary',axis=1,inplace=True)
df

        Name  Age      City
0      Krish   30    Mumbai
1  Siddharth   22  Jabalpur
2     Anshul   21    Jhansi
3       Yash   23    Indore

In [63]:
##ADDING THE AGE TO THE COLUMN
df['Age'] = df['Age']+1
print(df)
print("\n")

        Name  Age      City
0      Krish  311    Mumbai
1  Siddharth  231  Jabalpur
2     Anshul  221    Jhansi
3       Yash  241    Indore

In [69]:
##DROPING A PARTICULAR ROW

age_even = df[df['Age']%2 == 0].index

df.drop(age_even,inplace=True)
df

     Name  Age    City
2  Anshul   21  Jhansi
3    Yash   23  Indore

In [72]:
##Describe the statistics about dataframe
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000